name: "Dimmy Light Controller"
description: "Use the Dimmy light controller from VanPI to control your with Home Assistant"
version: "1.3.4"
slug: "dimmy_light_controller"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
log_level: info
privileged:
  - SYS_ADMIN
devices: 
  - /dev/i2c-1
device_tree: true
ports:
  5000/tcp: 5000
